### ISSUE TITLE
Please publish v0.0.2 on npm

### ISSUE THREAD

**Issue by TooTallNate** [component/indexof#3]
And/or add `tootallnate` as an owner to the `indexof` package on npm. Cheers @visionmedia!

**Comment by cbas** [comment]
@tj I think you are currently the owner on npm for this package. Would it be possible to either publish v0.0.2 or transfer ownership to another maintainer? Thanks!

```
> npm owner ls indexof
tjholowaychuk <tj@vision-media.ca>

> npm view indexof | grep maintainers
  maintainers: 'tjholowaychuk <tj@vision-media.ca>',
```

PS: Sorry to dig up this ancient issue.

**Comment by cbas** [comment]
@retrofox @TooTallNate @jongleberry Any chance of resolving the ownership? I'm happy to help.

Many packages continue to use `indexof` as a dependency. It had more npm downloads in the past day as `component-indexof` had in the past three months. :sweat_smile:
